### ISSUE TITLE
enrolment in storage course

### ISSUE THREAD

**Issue by rimacher** [kepeter/moodle-block_knowledge_sharing#11]
Hello,

This block only allows users enrolled as teachers in the storage course accesses the items.

We wanted to make a templates course but if we enroll all our teachers, the items might get deleted by them...

Is it possible to enable accesses to all users with editing capability regardless of their enrollment in the root course?

**Comment by kepeter** [comment]
Hi,

The need to enroll teacher is the need for authorization...
By enrolling teacher to the proper category (no need to enroll to course, but to category) you  - the site administrator - can give granular access, based on the actual roles of the teachers (actually you block them from accessing content not for them) in the organization...
So it is intentional...
If I understand you correctly you wan to remove this granularity and give a site-wide access to all the content...
It is possible, but please confirm that we are on the same page...

**Comment by kepeter** [comment]
b69a646ed3a61a7eadd6707d394e1156c91bef1a
